@startuml context_diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A person that wants to manage tasks")
Person(developer, "Developer", "Develops")
System(app, "Application", "Software system")
System(trello, "Trello", "Rest API, Persistent Data")

Rel(user, app, "Uses")
Rel(developer, app, "Develops and tests")
Rel(app, trello, "Create and update tasks")
Rel(trello, app, "Retrives tasks")
@endumls