name: DevOps Course CI
on: 
  push:
    # all branches  
    branches:
      - '**'
    paths:
      - todo_app/**
      - Dockerfile
      - pyproject.toml

  pull_request:
    branches:
      - master
  
  # every day the workflow is run at 3am
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag my-test-image .
    - run: docker run my-test-image ./todo_app/tests

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    needs: build
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Build Docker Image
        run: docker build --target prod -t todo-app:latest .  
      
      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PSW }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USER }}" --password-stdin

      - name: Tag the image
        run: docker tag todo-app:latest "${{ secrets.DOCKER_REGISTRY_USER }}/todo-app:latest"

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKER_REGISTRY_USER }}/todo-app:latest"
      
      - name: Update deploy image in Azure
        env:
          UNESCAPED_AZ_WEBHOOK: ${{ secrets.AZ_WEBHOOK_UPDATE_DOCKER_IMAGE }}
        run: curl -dH -X --fail POST ${{ secrets.AZ_WEBHOOK_UPDATE_DOCKER_IMAGE }}
       